# ATTENTION: IF YOU MODIFY THE FILE .yaml YOU MUST RERUN 

# =========================
# Global configuration file 
# =========================

# Directory containing all data files
data_dir: "data"

# Time range to process
first_year: 2022
last_year: 2024

# GitHub repository configuration
github:
  # Raw GitHub URL
  base_url: "https://raw.githubusercontent.com/rvm-courses/GasPrices/master/"

  # Files to download
  files:
    - "Prix2022S1.csv.gz"
    - "Prix2022S2.csv.gz"
    - "Prix2023.csv.gz"
    - "Prix2024.csv.gz"
    - "Stations2024.csv.gz"
    - "Services2024.csv.gz"



